"""vendor status and currency columns

Revision ID: 993f80e32aff
Revises: 2561082bd6b1
Create Date: 2026-08-12 20:04:26.395874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993f80e32aff'
down_revision: Union[str, Sequence[str], None] = '2561082bd6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('purchase_orders', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('vendors', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('vendors', sa.Column('created_by', sa.String(), server_default='human', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'created_by')
    op.drop_column('vendors', 'status')
    op.drop_column('purchase_orders', 'currency')
    op.drop_column('invoices', 'currency')
    # ### end Alembic commands ###
