/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description The queue: every invoice, newest first, with how its review turned out.
         */
        get: operations["list_invoices_invoices_get"];
        put?: never;
        /**
         * Create Invoice
         * @description Accept an invoice PDF and queue it for review.
         *
         *     Returns as soon as the row exists: a review takes 30-60s, longer than a
         *     client will hold a connection open. The id handed back is what the dashboard
         *     then polls.
         */
        post: operations["create_invoice_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice
         * @description One invoice, with the whole transcript of how it was decided.
         *
         *     An invoice with no run yet is a 200 with an empty transcript, not a 404: the
         *     row exists from upload, and this is where its review is watched happening.
         */
        get: operations["get_invoice_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Invoice File
         * @description The invoice's own PDF, for the upload-time preview.
         *
         *     Served straight from `raw_pdf_path`, so what a reviewer sees is provably the
         *     same bytes extraction ran against.
         */
        get: operations["get_invoice_file_invoices__invoice_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description What the agent is doing right now.
         *
         *     Polled about once a second, so it answers with the one call that changed
         *     rather than the transcript it belongs to. Outputs are left out of `latest`
         *     for the same reason: the ticker only renders the tool name and its input.
         */
        get: operations["get_activity_invoices__invoice_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Invoice
         * @description Clear an invoice for payment by human decision.
         */
        post: operations["approve_invoice_invoices__invoice_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoice_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Invoice
         * @description Refuse an invoice. Records the decision; nothing downstream acts on it.
         */
        post: operations["reject_invoice_invoices__invoice_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Log
         * @description Every human decision, newest first.
         *
         *     `before_state`/`after_state` carry the agent's decision and confidence at
         *     that moment, so a reviewer can see what they overrode as well as their own
         *     reasoning for it.
         */
        get: operations["list_audit_log_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending Vendors
         * @description Drafted payees waiting on a person to check them out of band.
         */
        get: operations["list_pending_vendors_vendors_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{vendor_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Vendor
         * @description Make a drafted payee payable, once a human has approved them.
         *
         *     When the agent meets an unknown payee it drafts a vendor, but a drafted
         *     vendor is not payable and the agent cannot change that. This endpoint is
         *     where a person, having checked the payee out of band, marks them active --
         *     and being active is what lets them be paid against at all.
         */
        post: operations["approve_vendor_vendors__vendor_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Activity
         * @description What the agent is doing right now. Polled about once a second.
         */
        Activity: {
            /** Status */
            status: string | null;
            latest: components["schemas"]["ActivityLatest"] | null;
            /** Call Count */
            call_count: number;
            /** Decision */
            decision: string | null;
        };
        /** ActivityLatest */
        ActivityLatest: {
            /** Tool */
            tool: string | null;
            /** Input */
            input: {
                [key: string]: unknown;
            } | null;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: string;
            /** Invoice Id */
            invoice_id: string;
            /** Vendor Name */
            vendor_name: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Action */
            action: string;
            /** Note */
            note: string | null;
            /** Agent Decision */
            agent_decision: string | null;
            /** Decided At */
            decided_at: string | null;
        };
        /** Body_create_invoice_invoices_post */
        Body_create_invoice_invoices_post: {
            /** File */
            file: string;
        };
        /** DecisionNote */
        DecisionNote: {
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /**
         * InvoiceAccepted
         * @description The 202 from an upload: enough to start polling with.
         */
        InvoiceAccepted: {
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /**
         * InvoiceDetail
         * @description A queue row plus the transcript of how it was decided.
         */
        InvoiceDetail: {
            /** Id */
            id: string;
            /** Invoice Number */
            invoice_number: string | null;
            /** Vendor Name */
            vendor_name: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string | null;
            /** Run Status */
            run_status: string | null;
            /** Decision */
            decision: string | null;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
            /** Due Date */
            due_date: string | null;
            /** Po Number */
            po_number: string | null;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCall"][];
            /** Policy Clauses */
            policy_clauses: components["schemas"]["PolicyClause"][];
        };
        /**
         * InvoiceSummary
         * @description One queue row.
         */
        InvoiceSummary: {
            /** Id */
            id: string;
            /** Invoice Number */
            invoice_number: string | null;
            /** Vendor Name */
            vendor_name: string | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string | null;
            /** Run Status */
            run_status: string | null;
            /** Decision */
            decision: string | null;
            /** Confidence */
            confidence: number | null;
            /** Reasoning */
            reasoning: string | null;
        };
        /** PendingVendor */
        PendingVendor: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Bank Details */
            bank_details: string | null;
        };
        /** PolicyClause */
        PolicyClause: {
            /** Section */
            section: string | null;
            /** Text */
            text: string | null;
        };
        /** ToolCall */
        ToolCall: {
            /** Tool */
            tool: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VendorApproved
         * @description The result of a human approving a drafted payee.
         */
        VendorApproved: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Approval Status */
            approval_status: string;
            /** Invoices Linked */
            invoices_linked: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_invoices_invoices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSummary"][];
                };
            };
        };
    };
    create_invoice_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_invoice_invoices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_file_invoices__invoice_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_invoices__invoice_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_invoice_invoices__invoice_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionNote"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_invoice_invoices__invoice_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionNote"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_log_audit_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
        };
    };
    list_pending_vendors_vendors_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingVendor"][];
                };
            };
        };
    };
    approve_vendor_vendors__vendor_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorApproved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
